# label: "Contact info page"
# description: "Show a contact's name and email"
# $contact_id: "{{request.contact.contact_vid }}"    
query contact_info($contact_id: String!) {
  CRM {
    contact(uniqueIdentifier: "id", uniqueIdentifierValue: $contact_id) {
      _metadata {
        id
      }
      firstname
      lastname
      email
      hs_additional_emails
      phone
      mobilephone
      address
      address2
      city
      state
      zip
      country
      work_address
      work_address_2
      work_city
      work_state
      work_zip
      other_address
      other_address_2
      other_city
      other_state
      medical_notes
      marital_status
      marital_status__new_
      birthday
      gender
      anniversary
      pushpay_payer_link
      pushpay_customer_id
      household_contact_type
      using_household_email
      grade
      associations {
        payments: deal_collection__contact_to_deal(
          filter: { pipeline__eq: "26389519" }
          orderBy: pushpay_payment_created__desc
        ) {
          limit
          total
          offset
          hasMore
          items {
            hs_object_id
            dealname
            amount
            closedate
            dealstage
            pipeline
            pushpay_account
            pushpay_merchant_payment_link
            pushpay_payment_campus
            pushpay_payment_created
            pushpay_payment_currency
            pushpay_payment_link
            pushpay_payment_method
            pushpay_payment_transaction_id
            pushpay_payment_fund_name
          }
        }
        registrations: p_registrations_collection__participant {
          items {
            hs_object_id
            event_name
            event_date
            household_id
            household_name
            contact_name
            associations {
              contacts:contact_collection__participant {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
              events: p_events_collection__registrations_to_events {
                items {
                  hs_object_id
                  name
                  banner_image
                  dynamic_page_slug
                  associations {
                    contact_collection__event_to_contact {
                      items {
                        hs_object_id
                        firstname
                        lastname
                        email
                      }
                    }
                  }
                }
              }
            }
          }
        }
        my_groups_lead: p_groups_collection__group_lead {
          items {
            hs_object_id
            name
          }
        }
        my_groups: p_groups_collection__group_to_contact {
          items {
            hs_object_id
            name
            featured_image
            dynamic_page_slug
            schedule
            associations {
              leaders:contact_collection__group_lead {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
              volunteer_leads: contact_collection__volunteer_lead {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
              members:contact_collection__volunteer {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
            }
          }
        }
        my_groups_volunteed_lead: p_groups_collection__volunteer_lead {
          items {
            hs_object_id
            name
          }
        }
        my_groups_volunteer: p_groups_collection__volunteer {
          items {
            hs_object_id
            name
          }
        }
        teams: p_teams_collection__volunteer_team_to_contact {
          items {
            hs_object_id
            team_name
            featured_image
          }
        }
        my_teams: p_teams_collection__team_lead{
          items {
            hs_object_id
            team_name
						featured_image
            page_slug
            primary_team_lead
            serve_schedule
            application_form_link
            associations {
              leaders:contact_collection__team_lead {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
              members: contact_collection__team_member {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                }
              }
            }
          }
        }
        volunteer_activity :p_volunteer_activities_collection__volunteer_activity_to_contact {
          items {
            hs_object_id
            name
            location
            note
            schedule_preference
            team_name
            hs_pipeline
            hs_pipeline_stage
            status
          }
        }
        events: p_events_collection__event_to_contact {
          items {
            hs_object_id
            name
          }
        }
        households: p_households_collection__type_2_17952728_to_contact(limit: 1) {
          items {
            hs_object_id
            family_name
            associations {
              members: contact_collection__type_2_17952728_to_contact {
                items {
                  hs_object_id
                  firstname
                  lastname
                  email
                  gender
                  grade
                  birthday
                  email
                  phone
                  household_contact_type
                  using_household_email
                  associations {
                    registrations: p_registrations_collection__participant {
                      items {
                        hs_object_id
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}